Distribute sampling bias
fission-suite/webnative pull request #364
Opened 2022-03-29 10:39 UTC by appcypher

## Summary

This PR fixes the following **issues**

* [x] Sampling bias towards low numbers

Currently pin sampling method has a slight bias towards low numbers (0-5). This PR fixes that by distributing the bias more evenly to higher numbers which is a simpler solution than trying to get rid of the bias.

## Test plan (required)

Making sure existing tests around pin generation still pass. 

```bash
yarn test:prod -g "generates a pin and challenge message"
```

## Closing issues

Fixes #359

2022-03-29 12:48 UTC, matheus23 requested changes
Thanks for tackling this! :)

The method to get rid of the bias isn't familiar to me and it's not clear to me how this gets rid of the bias. Is there some resource I can read to understand it better? If so, we should probably also include a comment in the code linking to it.

I should've probably added this to the issue when I created it, but I was thinking of something like this: https://research.kudelskisecurity.com/2020/07/28/the-definitive-guide-to-modulo-bias-and-how-to-avoid-it/

This is not me saying "that's how it should be done". If there's a method that doesn't need to re-sample to reduce bias, then it seems superior!

2022-03-29 16:34 UTC, expede commented
I probably should have fleshed out that comment a lot more 😅 We don't want bias in the number; ideally they're fully evenly distributed in order to make attacking this code difficult. It's an edge case, but security is important. I was more gesturing at multiple options and that we're going to start more consistently phrasing things as stories rather than as specific solutions when we start scrum next week :)

2022-03-29 16:39 UTC, appcypher commented
Alright. Let me fix that

2022-03-30 10:11 UTC, matheus23 approved these changes
Perfect, this is good to go! :tada: 

(Just make sure to release the new keystore-idb version before merging this & make sure that the tests run :+1: )

2022-03-31 13:35 UTC, merged